version: '3'

services:
  books-app:
    build: ./books-app
    ports:
      - "5002:5002"

  authors-app:
    build: ./authors-app
    ports:
      - "5003:5002"

  main-app:
    build: ./main-app
    ports:
      - "5004:5004"
    depends_on:
      - books-app
      - authors-app
